name: Tests
on:
  pull_request:
    branches: [master]

env:
  NODE_VERSION: '16'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install
      run: yarn install --frozen-lockfile
    - name: ESLint
      run: yarn lint:js
    - name: Types
      run: yarn tsc --noEmit

  tests_floating:
    name: Floating
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install
      run: yarn install --no-lockfile --non-interactive
    - name: Test
      run: yarn test:ember

  tests_lts_releases:
    name: LTS & Releases
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scenario:
        - ember-lts-3.24
        - ember-lts-3.28
        - ember-release
        - ember-beta
        - ember-canary
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install
      run: yarn install --frozen-lockfile
    - name: Test with ${{ matrix.scenario }}
      run: ./node_modules/.bin/ember try:one ${{ matrix.scenario }}

  tests_integration:
    name: Integration
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ember_app:
        - "classic/3.4"
        - "classic/3.14"
        - "octane/3.14"
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Test
      env:
        EMBER_APP: ${{ matrix.ember_app }}
      run: |
        cd tests/-ember-apps/$EMBER_APP/
        yarn
        ./node_modules/.bin/ember test
