name: Tests
on:
  pull_request:
    branches: [master]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install
      run: yarn install
    - name: ESLint
      run: yarn lint:js
    - name: Types
      run: yarn tsc --noEmit

  tests_floating:
    name: Floating
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install
      run: yarn install --no-lockfile --non-interactive
    - name: Test
      run: yarn test

  tests_lts_releases:
    name: LTS & Releases
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scenario:
        - "ember-lts-3.4"
        - "ember-lts-3.8"
        - "ember-lts-3.12"
        - "ember-release"
        - "ember-beta"
        - "ember-canary"
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install
      run: yarn install
    - name: Test with ${{ matrix.scenario }}
      run: yarn test:try-one ${{ matrix.scenario }}

  tests_integration:
    name: Integration
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ember_app:
        - "classic/3.4"
        - "classic/3.14"
        - "octane/3.14"
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Test
      env:
        EMBER_APP: ${{ matrix.ember_app }}
      run: |
        cd tests/-ember-apps/$EMBER_APP/
        yarn
        yarn test
